# Generated by Django 4.1.3 on 2022-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_admin_a_de_admin_a_wh'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_accur',
            field=models.FloatField(default=0, verbose_name='정확도'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_check',
            field=models.IntegerField(default=0, verbose_name='검출 유무'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='default.jpg', unique=True, upload_to='images/'),
        ),
    ]
