# Generated by Django 4.0.3 on 2022-11-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_admin_a_de_admin_a_wh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='default.jpg', unique=True, upload_to='images/'),
        ),
    ]
