# Generated by Django 4.1.3 on 2022-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0003_car_car_accur_car_car_check_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(unique=True, upload_to='images/'),
        ),
    ]
